### ISSUE TITLE
Api Only Returns Recent 20 Items

### ISSUE THREAD

**Issue by mailtokamalnayan** [DanielOliver/gatsby-source-goodreads#1]
I am not sure if this is an API limitation or I am not implementing correctly, but the API only returns the recent 20 results.

![image](https://user-images.githubusercontent.com/2495633/55846508-8067cc00-5b78-11e9-94c7-f4ea1d67e547.png)

I have more than 50 books in "read" shelf.

**Comment by DanielOliver** [comment]
Good evening!  Thank you for letting me know about this.  No artificial limitation is being passed to the API: https://github.com/DanielOliver/gatsby-source-goodreads/blob/218dfaa9b4d5f5bf2395030c3718070c8211f7ed/gatsby-node.js#L18   

The Goodreads API doesn't specify a limit of 20, but I wouldn't be surprised if there were.  https://www.goodreads.com/api/index#reviews.list  
```Parameters:
    v: 2
    id: Goodreads id of the user
    shelf: read, currently-reading, to-read, etc. (optional)
    sort: title, author, cover, rating, year_pub, date_pub, date_pub_edition, date_started, date_read, date_updated, date_added, recommender, avg_rating, num_ratings, review, read_count, votes, random, comments, notes, isbn, isbn13, asin, num_pages, format, position, shelves, owned, date_purchased, purchase_location, condition (optional)
    search[query]: query text to match against member's books (optional)
    order: a, d (optional)
    page: 1-N (optional)
    per_page: 1-200 (optional)
    key: Developer key (required)
```

I must admit that all uses I've had so far have not been for as many books as you have in any one list.  Unfortunately, I don't have the time to really debug this and fix it this week.  I wonder if the other gatsby goodread packages ran into this problem.

**Comment by mailtokamalnayan** [comment]
Thank you for the response.

I will use other Goodreads API and update.

**Comment by mailtokamalnayan** [comment]
I tried [@jamesdanylik/gatsby-source-goodreads](https://www.gatsbyjs.org/packages/@jamesdanylik/gatsby-source-goodreads/?=goodread) and it returns the full list.

**Comment by DanielOliver** [comment]
I really appreciate the update.  I've been out of pocket.  In the next few weeks I'm either going to update my package or formally recommend the other package.  The problem seems to be that the use case I have for my own package here is not quite the general use-case it's marketed as solving.  I'm sorry that you had to do the run-around to find a package that worked for you.  I'm going to go ahead and close this issue on the assumption that you've found a solution.
