### ISSUE TITLE
Consider deprecating in favour of @jamesdanylik/gatsby-source-goodreads

### ISSUE THREAD

**Issue by madeleineostoja** [DanielOliver/gatsby-source-goodreads#4]
Thanks for publishing this source! After setting it up and running into a few limitations I found the alternative [@jamesdanylik/gatsby-source-goodreads](https://www.gatsbyjs.org/packages/@jamesdanylik/gatsby-source-goodreads/) package, which seems to address a few of the issues this one has. Since it seems this project isn't actively developed any more, have you considered deprecating in favour of that package? 

Only because with this being an unscoped name it's the first thing you find when searching for a goodreads source for Gatsby.

Appreciate the hard work either way!

**Comment by DanielOliver** [comment]
I agree with your conclusion. Thank you for bringing this up.  I haven't actively been maintaining this package as well.
